name: DevSecOps Spring Boot Pipeline


on:
  push:
    branches: [ "main" ]
permissions:
  contents: read
  security-events: write
  actions: read
jobs:
  devsecops:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # 1. SAST CodeQL
      - name: Init CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: java

      - name: Run CodeQL
        uses: github/codeql-action/analyze@v3

      # 2. Scan d√©pendances Maven
      - name: Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: "spring-devsecops"
          format: "HTML"

      # 3. Build image Docker
      - name: Build Docker image
        run: docker build -t spring-devsecops .

      # 4. Scan image Docker
      - name: Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: spring-devsecops
          severity: CRITICAL,HIGH
          exit-code: 1
